const PRODUCTS_URL='assets/products.json';let products=[];let bag=JSON.parse(localStorage.getItem('nestaBag')||'[]');
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function money(v){return Number(String(v).replace('$',''))}
function saveBag(){localStorage.setItem('nestaBag',JSON.stringify(bag));renderBagCount();renderBag()}
function renderBagCount(){const el=$('#bagCount');if(el)el.textContent=bag.length}
function card(p,i){return `<article class="product-card"><div class="product-image"><img src="${p.image}" alt="${p.name}" loading="lazy"></div><div class="product-content"><div class="product-cat">${p.category}</div><h3 class="product-title">${p.name}</h3><p class="product-desc">${p.description}</p><div class="price">${p.price}</div><div class="product-actions"><button class="add-btn" data-add="${i}">Add to bag</button><button class="save-btn">♡ Save</button></div></div></article>`}
function renderGrid(el,list){if(!el)return;el.innerHTML=list.map((p)=>card(p,products.indexOf(p))).join('');el.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{bag.push(products[+b.dataset.add]);saveBag();openOverlay('bagPanel')});el.querySelectorAll('.save-btn').forEach(b=>b.onclick=()=>b.textContent=b.textContent.includes('Saved')?'♡ Save':'♥ Saved')}
function renderBag(){const el=$('#bagItems');const total=$('#bagTotal');if(!el)return;if(!bag.length){el.innerHTML='<p style="color:var(--muted)">Your bag is empty.</p>';if(total)total.textContent='$0.00';return}el.innerHTML=bag.map((p,i)=>`<div class="bag-row"><img src="${p.image}" alt="${p.name}"><div><strong>${p.name}</strong><span>${p.price}</span></div><button class="remove" data-remove="${i}">Remove</button></div>`).join('');el.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{bag.splice(+b.dataset.remove,1);saveBag()});if(total)total.textContent='$'+bag.reduce((s,p)=>s+money(p.price),0).toFixed(2)}
function openOverlay(id){const el=$('#'+id);if(el)el.classList.add('open')}function closeOverlays(){$$('.overlay').forEach(x=>x.classList.remove('open'))}
async function init(){products=await fetch(PRODUCTS_URL).then(r=>r.json());renderBagCount();renderBag();const featured=$('#featuredGrid');if(featured)renderGrid(featured,products.slice(0,8));const shopGrid=$('#shopGrid');if(shopGrid)initShop(shopGrid);const search=$('#searchInput');if(search)search.oninput=()=>{const q=search.value.toLowerCase().trim();const out=$('#searchResults');if(!q){out.innerHTML='';return}const hits=products.filter(p=>(p.name+' '+p.category+' '+p.description).toLowerCase().includes(q)).slice(0,8);out.innerHTML=hits.map(p=>`<div class="search-result"><img src="${p.image}" alt=""><div><strong>${p.name}</strong><small>${p.category} · ${p.price}</small></div></div>`).join('')||'<p style="color:var(--muted)">No matching essentials yet.</p>'}}
function initShop(grid){let cat=new URLSearchParams(location.search).get('cat')||'All';let sort='featured';const buttons=$$('.shop-area aside button');function draw(){let list=cat==='All'?products:products.filter(p=>p.category===cat);if(sort==='low')list=[...list].sort((a,b)=>money(a.price)-money(b.price));if(sort==='high')list=[...list].sort((a,b)=>money(b.price)-money(a.price));renderGrid(grid,list);const c=$('#resultCount');if(c)c.textContent=`${list.length} products`;buttons.forEach(b=>b.classList.toggle('active',b.dataset.cat===cat))}buttons.forEach(b=>b.onclick=()=>{cat=b.dataset.cat;draw()});const s=$('#sort');if(s)s.onchange=()=>{sort=s.value;draw()};draw()}
$$('#searchOpen').forEach(b=>b.onclick=()=>openOverlay('searchPanel'));$$('#bagOpen').forEach(b=>b.onclick=()=>openOverlay('bagPanel'));$$('[data-close]').forEach(b=>b.onclick=closeOverlays);$$('.overlay').forEach(o=>o.onclick=e=>{if(e.target===o)closeOverlays()});const news=$('#newsletter');if(news)news.onsubmit=e=>{e.preventDefault();alert('Thanks for joining NESTA.');news.reset()};init();
